# Data Cleaning in Pandas

In [1]:
#import library
import pandas as pd

In [2]:
df = pd.read_excel(r'C:\Users\ASUS\OneDrive\Desktop\python project\Customer Call List.xlsx')

In [3]:
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,True
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes,False
2,1003,Walter,/White,7066950392,298 Drugs Driveway,N,NaN,True
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No,True
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,True
6,1007,Jeff,Winger,NaN,1209 South Street,No,No,False
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No,False
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN,False
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No,True
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No,True
11,1012,Harry,...Potter,7066950392,2394 Hogwarts Avenue,Y,NaN,True
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,False
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No,False
14,1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,No,False
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,False
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No,False
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN,True
18,1019,Creed,Braton,N/a,N/a,N/a,Yes,True
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True
20,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True

In [45]:
#remove duplicate value
df = df.drop_duplicates()
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Stree Address,State,Zip
0,1001,Frodo,Baggins,123--54-5-54,"123 Shire Lane, Shire",Y,N,123 Shire Lane,Shire,
2,1003,Walter,/White,,298 Drugs Driveway,N,,298 Drugs Driveway,,
4,1005,Jon,Snow,876--67-8-34,123 Dragons Road,Y,N,123 Dragons Road,,
6,1007,Jeff,Winger,,1209 South Street,N,N,1209 South Street,,
7,1008,Sherlock,Holmes,876--67-8-34,98 Clue Drive,N,N,98 Clue Drive,,
8,1009,Gandalf,,,123 Middle Earth,Y,,123 Middle Earth,,
9,1010,Peter,Parker,123--54-5-54,"25th Main Street, New York",Y,N,25th Main Street,New York,
10,1011,Samwise,Gamgee,,"612 Shire Lane, Shire",Y,N,612 Shire Lane,Shire,
11,1012,Harry,...Potter,,2394 Hogwarts Avenue,Y,,2394 Hogwarts Avenue,,
12,1013,Don,Draper,123--54-3-23,2039 Main Street,Y,N,2039 Main Street,,
13,1014,Leslie,Knope,876--67-8-34,343 City Parkway,Y,N,343 City Parkway,,
14,1015,Toby,Flenderson_,304--76-2-24,214 HR Avenue,N,N,214 HR Avenue,,
15,1016,Ron,Weasley,123--54-5-54,2395 Hogwarts Avenue,N,N,2395 Hogwarts Avenue,,
16,1017,Michael,Scott,123--64-3-97,"121 Paper Avenue, Pennsylvania",Y,N,121 Paper Avenue,Pennsylvania,
17,1018,Clark,Kent,,3498 Super Lane,Y,,3498 Super Lane,,
19,1020,Anakin,Skywalker,876--67-8-34,"910 Tatooine Road, Tatooine",Y,N,910 Tatooine Road,Tatooine,

In [32]:
df = df.drop(columns = 'Not_Useful_Column')
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Stree Address,State,Zip
0,1001,Frodo,Baggins,123--54-5-54,"123 Shire Lane, Shire",Y,N,123 Shire Lane,Shire,None
1,1002,Abed,Nadir,123--64-3-97,93 West Main Street,N,Y,93 West Main Street,None,None
2,1003,Walter,/White,,298 Drugs Driveway,N,NaN,298 Drugs Driveway,None,None
3,1004,Dwight,Schrute,123--54-3-23,"980 Paper Avenue, Pennsylvania, 18503",Y,Y,980 Paper Avenue,Pennsylvania,18503
4,1005,Jon,Snow,876--67-8-34,123 Dragons Road,Y,N,123 Dragons Road,None,None
5,1006,Ron,Swanson,304--76-2-24,768 City Parkway,Y,Y,768 City Parkway,None,None
6,1007,Jeff,Winger,,1209 South Street,N,N,1209 South Street,None,None
7,1008,Sherlock,Holmes,876--67-8-34,98 Clue Drive,N,N,98 Clue Drive,None,None
8,1009,Gandalf,NaN,,123 Middle Earth,Y,NaN,123 Middle Earth,None,None
9,1010,Peter,Parker,123--54-5-54,"25th Main Street, New York",Y,N,25th Main Street,New York,None
10,1011,Samwise,Gamgee,,"612 Shire Lane, Shire",Y,N,612 Shire Lane,Shire,None
11,1012,Harry,...Potter,,2394 Hogwarts Avenue,Y,NaN,2394 Hogwarts Avenue,None,None
12,1013,Don,Draper,123--54-3-23,2039 Main Street,Y,N,2039 Main Street,None,None
13,1014,Leslie,Knope,876--67-8-34,343 City Parkway,Y,N,343 City Parkway,None,None
14,1015,Toby,Flenderson_,304--76-2-24,214 HR Avenue,N,N,214 HR Avenue,None,None
15,1016,Ron,Weasley,123--54-5-54,2395 Hogwarts Avenue,N,N,2395 Hogwarts Avenue,None,None
16,1017,Michael,Scott,123--64-3-97,"121 Paper Avenue, Pennsylvania",Y,N,121 Paper Avenue,Pennsylvania,None
17,1018,Clark,Kent,,3498 Super Lane,Y,NaN,3498 Super Lane,None,None
18,1019,Creed,Braton,,N/a,N/a,Y,N/a,None,None
19,1020,Anakin,Skywalker,876--67-8-34,"910 Tatooine Road, Tatooine",Y,N,910 Tatooine Road,Tatooine,None
20,1020,Anakin,Skywalker,876--67-8-34,"910 Tatooine Road, Tatooine",Y,N,910 Tatooine Road,Tatooine,None

In [13]:
#strip, lstrip, rstrip ==> remove extra white space and other character from the left and right of the column
df['Last_Name'] = df['Last_Name'].str.lstrip("/")
df['Last_Name'] = df['Last_Name'].str.lstrip("...") #remove white space from the left sied
df['Last_Name'] = df['Last_Name'].str.rstrip("_") #remove white space from the right side
df

#the easy way
df['Last_Name'] = df['Last_Name'].str.rstrip("123._/") #this methods removes all of them which is inside the qoutes

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes
2,1003,Walter,White,7066950392,298 Drugs Driveway,N,NaN
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes
6,1007,Jeff,Winger,NaN,1209 South Street,No,No
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No
11,1012,Harry,Potter,7066950392,2394 Hogwarts Avenue,Y,NaN
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No
14,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,No
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN
18,1019,Creed,Braton,N/a,N/a,N/a,Yes
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N

In [8]:
#Standardize the phone number into specific format
df['Phone_Number'] = df['Phone_Number'].str.replace('[^a-zA-Z0-9]','')
df

C:\Users\ASUS\AppData\Local\Temp\ipykernel_4200\3998479705.py:2: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Phone_Number'] = df['Phone_Number'].str.replace('[^a-zA-Z0-9]','')

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
0,1001,Frodo,Baggins,1235455421,"123 Shire Lane, Shire",Yes,No,True
1,1002,Abed,Nadir,1236439775,93 West Main Street,No,Yes,False
2,1003,Walter,/White,NaN,298 Drugs Driveway,N,NaN,True
3,1004,Dwight,Schrute,1235432345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True
4,1005,Jon,Snow,8766783469,123 Dragons Road,Y,No,True
5,1006,Ron,Swanson,3047622467,768 City Parkway,Yes,Yes,True
6,1007,Jeff,Winger,NaN,1209 South Street,No,No,False
7,1008,Sherlock,Holmes,8766783469,98 Clue Drive,N,No,False
8,1009,Gandalf,NaN,Na,123 Middle Earth,Yes,NaN,False
9,1010,Peter,Parker,1235455421,"25th Main Street, New York",Yes,No,True
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No,True
11,1012,Harry,...Potter,NaN,2394 Hogwarts Avenue,Y,NaN,True
12,1013,Don,Draper,1235432345,2039 Main Street,Yes,N,False
13,1014,Leslie,Knope,8766783469,343 City Parkway,Yes,No,False
14,1015,Toby,Flenderson_,3047622467,214 HR Avenue,N,No,False
15,1016,Ron,Weasley,1235455421,2395 Hogwarts Avenue,No,N,False
16,1017,Michael,Scott,1236439775,"121 Paper Avenue, Pennsylvania",Yes,No,False
17,1018,Clark,Kent,NaN,3498 Super Lane,Y,NaN,True
18,1019,Creed,Braton,Na,N/a,N/a,Yes,True
19,1020,Anakin,Skywalker,8766783469,"910 Tatooine Road, Tatooine",Yes,N,True
20,1020,Anakin,Skywalker,8766783469,"910 Tatooine Road, Tatooine",Yes,N,True

In [20]:
#standardize the phone number using lamda expression
df['Phone_Number'] = df['Phone_Number'].apply(lambda x:str(x)) #convert every value into string data type
df['Phone_Number'] = df['Phone_Number'].apply(lambda x: x[0:3] + '-' + x[3:6] + '-' + x[6:10]) #split every 3 digits with -
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
0,1001,Frodo,Baggins,123--54-5-54,"123 Shire Lane, Shire",Yes,No,True
1,1002,Abed,Nadir,123--64-3-97,93 West Main Street,No,Yes,False
2,1003,Walter,/White,nan----,298 Drugs Driveway,N,NaN,True
3,1004,Dwight,Schrute,123--54-3-23,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True
4,1005,Jon,Snow,876--67-8-34,123 Dragons Road,Y,No,True
5,1006,Ron,Swanson,304--76-2-24,768 City Parkway,Yes,Yes,True
6,1007,Jeff,Winger,nan----,1209 South Street,No,No,False
7,1008,Sherlock,Holmes,876--67-8-34,98 Clue Drive,N,No,False
8,1009,Gandalf,NaN,Na----,123 Middle Earth,Yes,NaN,False
9,1010,Peter,Parker,123--54-5-54,"25th Main Street, New York",Yes,No,True
10,1011,Samwise,Gamgee,nan----,"612 Shire Lane, Shire",Yes,No,True
11,1012,Harry,...Potter,nan----,2394 Hogwarts Avenue,Y,NaN,True
12,1013,Don,Draper,123--54-3-23,2039 Main Street,Yes,N,False
13,1014,Leslie,Knope,876--67-8-34,343 City Parkway,Yes,No,False
14,1015,Toby,Flenderson_,304--76-2-24,214 HR Avenue,N,No,False
15,1016,Ron,Weasley,123--54-5-54,2395 Hogwarts Avenue,No,N,False
16,1017,Michael,Scott,123--64-3-97,"121 Paper Avenue, Pennsylvania",Yes,No,False
17,1018,Clark,Kent,nan----,3498 Super Lane,Y,NaN,True
18,1019,Creed,Braton,Na----,N/a,N/a,Yes,True
19,1020,Anakin,Skywalker,876--67-8-34,"910 Tatooine Road, Tatooine",Yes,N,True
20,1020,Anakin,Skywalker,876--67-8-34,"910 Tatooine Road, Tatooine",Yes,N,True

In [21]:
#replace the value
df['Phone_Number'] = df['Phone_Number'].str.replace('nan----', '')
df['Phone_Number'] = df['Phone_Number'].str.replace('Na----', '')
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
0,1001,Frodo,Baggins,123--54-5-54,"123 Shire Lane, Shire",Yes,No,True
1,1002,Abed,Nadir,123--64-3-97,93 West Main Street,No,Yes,False
2,1003,Walter,/White,,298 Drugs Driveway,N,NaN,True
3,1004,Dwight,Schrute,123--54-3-23,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True
4,1005,Jon,Snow,876--67-8-34,123 Dragons Road,Y,No,True
5,1006,Ron,Swanson,304--76-2-24,768 City Parkway,Yes,Yes,True
6,1007,Jeff,Winger,,1209 South Street,No,No,False
7,1008,Sherlock,Holmes,876--67-8-34,98 Clue Drive,N,No,False
8,1009,Gandalf,NaN,,123 Middle Earth,Yes,NaN,False
9,1010,Peter,Parker,123--54-5-54,"25th Main Street, New York",Yes,No,True
10,1011,Samwise,Gamgee,,"612 Shire Lane, Shire",Yes,No,True
11,1012,Harry,...Potter,,2394 Hogwarts Avenue,Y,NaN,True
12,1013,Don,Draper,123--54-3-23,2039 Main Street,Yes,N,False
13,1014,Leslie,Knope,876--67-8-34,343 City Parkway,Yes,No,False
14,1015,Toby,Flenderson_,304--76-2-24,214 HR Avenue,N,No,False
15,1016,Ron,Weasley,123--54-5-54,2395 Hogwarts Avenue,No,N,False
16,1017,Michael,Scott,123--64-3-97,"121 Paper Avenue, Pennsylvania",Yes,No,False
17,1018,Clark,Kent,,3498 Super Lane,Y,NaN,True
18,1019,Creed,Braton,,N/a,N/a,Yes,True
19,1020,Anakin,Skywalker,876--67-8-34,"910 Tatooine Road, Tatooine",Yes,N,True
20,1020,Anakin,Skywalker,876--67-8-34,"910 Tatooine Road, Tatooine",Yes,N,True

In [25]:
#split the column into individual base on the dilimeter
df['Address'].str.split(',', 2 , expand = True)

                       0              1       2
0         123 Shire Lane          Shire    None
1    93 West Main Street           None    None
2     298 Drugs Driveway           None    None
3       980 Paper Avenue   Pennsylvania   18503
4       123 Dragons Road           None    None
5       768 City Parkway           None    None
6      1209 South Street           None    None
7          98 Clue Drive           None    None
8       123 Middle Earth           None    None
9       25th Main Street       New York    None
10        612 Shire Lane          Shire    None
11  2394 Hogwarts Avenue           None    None
12      2039 Main Street           None    None
13      343 City Parkway           None    None
14         214 HR Avenue           None    None
15  2395 Hogwarts Avenue           None    None
16      121 Paper Avenue   Pennsylvania    None
17       3498 Super Lane           None    None
18                   N/a           None    None
19     910 Tatooine Road       Tatooine    None
20     910 Tatooine Road       Tatooine    None

In [26]:
#name every individual columns
df[['Stree Address','State','Zip']] = df['Address'].str.split(',', 2 , expand = True)

In [27]:
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column,Stree Address,State,Zip
0,1001,Frodo,Baggins,123--54-5-54,"123 Shire Lane, Shire",Yes,No,True,123 Shire Lane,Shire,None
1,1002,Abed,Nadir,123--64-3-97,93 West Main Street,No,Yes,False,93 West Main Street,None,None
2,1003,Walter,/White,,298 Drugs Driveway,N,NaN,True,298 Drugs Driveway,None,None
3,1004,Dwight,Schrute,123--54-3-23,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True,980 Paper Avenue,Pennsylvania,18503
4,1005,Jon,Snow,876--67-8-34,123 Dragons Road,Y,No,True,123 Dragons Road,None,None
5,1006,Ron,Swanson,304--76-2-24,768 City Parkway,Yes,Yes,True,768 City Parkway,None,None
6,1007,Jeff,Winger,,1209 South Street,No,No,False,1209 South Street,None,None
7,1008,Sherlock,Holmes,876--67-8-34,98 Clue Drive,N,No,False,98 Clue Drive,None,None
8,1009,Gandalf,NaN,,123 Middle Earth,Yes,NaN,False,123 Middle Earth,None,None
9,1010,Peter,Parker,123--54-5-54,"25th Main Street, New York",Yes,No,True,25th Main Street,New York,None
10,1011,Samwise,Gamgee,,"612 Shire Lane, Shire",Yes,No,True,612 Shire Lane,Shire,None
11,1012,Harry,...Potter,,2394 Hogwarts Avenue,Y,NaN,True,2394 Hogwarts Avenue,None,None
12,1013,Don,Draper,123--54-3-23,2039 Main Street,Yes,N,False,2039 Main Street,None,None
13,1014,Leslie,Knope,876--67-8-34,343 City Parkway,Yes,No,False,343 City Parkway,None,None
14,1015,Toby,Flenderson_,304--76-2-24,214 HR Avenue,N,No,False,214 HR Avenue,None,None
15,1016,Ron,Weasley,123--54-5-54,2395 Hogwarts Avenue,No,N,False,2395 Hogwarts Avenue,None,None
16,1017,Michael,Scott,123--64-3-97,"121 Paper Avenue, Pennsylvania",Yes,No,False,121 Paper Avenue,Pennsylvania,None
17,1018,Clark,Kent,,3498 Super Lane,Y,NaN,True,3498 Super Lane,None,None
18,1019,Creed,Braton,,N/a,N/a,Yes,True,N/a,None,None
19,1020,Anakin,Skywalker,876--67-8-34,"910 Tatooine Road, Tatooine",Yes,N,True,910 Tatooine Road,Tatooine,None
20,1020,Anakin,Skywalker,876--67-8-34,"910 Tatooine Road, Tatooine",Yes,N,True,910 Tatooine Road,Tatooine,None

In [33]:
#Replace the sepcific value 
df['Paying Customer'] = df['Paying Customer'].str.replace('No', 'N')
df['Paying Customer'] = df['Paying Customer'].str.replace('Yes', 'Y')

df['Do_Not_Contact'] = df['Do_Not_Contact'].str.replace('No', 'N')
df['Do_Not_Contact'] = df['Do_Not_Contact'].str.replace('Yes', 'Y')
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Stree Address,State,Zip
0,1001,Frodo,Baggins,123--54-5-54,"123 Shire Lane, Shire",Y,N,123 Shire Lane,Shire,None
1,1002,Abed,Nadir,123--64-3-97,93 West Main Street,N,Y,93 West Main Street,None,None
2,1003,Walter,/White,,298 Drugs Driveway,N,NaN,298 Drugs Driveway,None,None
3,1004,Dwight,Schrute,123--54-3-23,"980 Paper Avenue, Pennsylvania, 18503",Y,Y,980 Paper Avenue,Pennsylvania,18503
4,1005,Jon,Snow,876--67-8-34,123 Dragons Road,Y,N,123 Dragons Road,None,None
5,1006,Ron,Swanson,304--76-2-24,768 City Parkway,Y,Y,768 City Parkway,None,None
6,1007,Jeff,Winger,,1209 South Street,N,N,1209 South Street,None,None
7,1008,Sherlock,Holmes,876--67-8-34,98 Clue Drive,N,N,98 Clue Drive,None,None
8,1009,Gandalf,NaN,,123 Middle Earth,Y,NaN,123 Middle Earth,None,None
9,1010,Peter,Parker,123--54-5-54,"25th Main Street, New York",Y,N,25th Main Street,New York,None
10,1011,Samwise,Gamgee,,"612 Shire Lane, Shire",Y,N,612 Shire Lane,Shire,None
11,1012,Harry,...Potter,,2394 Hogwarts Avenue,Y,NaN,2394 Hogwarts Avenue,None,None
12,1013,Don,Draper,123--54-3-23,2039 Main Street,Y,N,2039 Main Street,None,None
13,1014,Leslie,Knope,876--67-8-34,343 City Parkway,Y,N,343 City Parkway,None,None
14,1015,Toby,Flenderson_,304--76-2-24,214 HR Avenue,N,N,214 HR Avenue,None,None
15,1016,Ron,Weasley,123--54-5-54,2395 Hogwarts Avenue,N,N,2395 Hogwarts Avenue,None,None
16,1017,Michael,Scott,123--64-3-97,"121 Paper Avenue, Pennsylvania",Y,N,121 Paper Avenue,Pennsylvania,None
17,1018,Clark,Kent,,3498 Super Lane,Y,NaN,3498 Super Lane,None,None
18,1019,Creed,Braton,,N/a,N/a,Y,N/a,None,None
19,1020,Anakin,Skywalker,876--67-8-34,"910 Tatooine Road, Tatooine",Y,N,910 Tatooine Road,Tatooine,None
20,1020,Anakin,Skywalker,876--67-8-34,"910 Tatooine Road, Tatooine",Y,N,910 Tatooine Road,Tatooine,None

In [41]:
df = df.replace('N/a','')
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Stree Address,State,Zip
0,1001,Frodo,Baggins,123--54-5-54,"123 Shire Lane, Shire",Y,N,123 Shire Lane,Shire,None
1,1002,Abed,Nadir,123--64-3-97,93 West Main Street,N,Y,93 West Main Street,None,None
2,1003,Walter,/White,,298 Drugs Driveway,N,NaN,298 Drugs Driveway,None,None
3,1004,Dwight,Schrute,123--54-3-23,"980 Paper Avenue, Pennsylvania, 18503",Y,Y,980 Paper Avenue,Pennsylvania,18503
4,1005,Jon,Snow,876--67-8-34,123 Dragons Road,Y,N,123 Dragons Road,None,None
5,1006,Ron,Swanson,304--76-2-24,768 City Parkway,Y,Y,768 City Parkway,None,None
6,1007,Jeff,Winger,,1209 South Street,N,N,1209 South Street,None,None
7,1008,Sherlock,Holmes,876--67-8-34,98 Clue Drive,N,N,98 Clue Drive,None,None
8,1009,Gandalf,NaN,,123 Middle Earth,Y,NaN,123 Middle Earth,None,None
9,1010,Peter,Parker,123--54-5-54,"25th Main Street, New York",Y,N,25th Main Street,New York,None
10,1011,Samwise,Gamgee,,"612 Shire Lane, Shire",Y,N,612 Shire Lane,Shire,None
11,1012,Harry,...Potter,,2394 Hogwarts Avenue,Y,NaN,2394 Hogwarts Avenue,None,None
12,1013,Don,Draper,123--54-3-23,2039 Main Street,Y,N,2039 Main Street,None,None
13,1014,Leslie,Knope,876--67-8-34,343 City Parkway,Y,N,343 City Parkway,None,None
14,1015,Toby,Flenderson_,304--76-2-24,214 HR Avenue,N,N,214 HR Avenue,None,None
15,1016,Ron,Weasley,123--54-5-54,2395 Hogwarts Avenue,N,N,2395 Hogwarts Avenue,None,None
16,1017,Michael,Scott,123--64-3-97,"121 Paper Avenue, Pennsylvania",Y,N,121 Paper Avenue,Pennsylvania,None
17,1018,Clark,Kent,,3498 Super Lane,Y,NaN,3498 Super Lane,None,None
18,1019,Creed,Braton,,,,Y,,None,None
19,1020,Anakin,Skywalker,876--67-8-34,"910 Tatooine Road, Tatooine",Y,N,910 Tatooine Road,Tatooine,None
20,1020,Anakin,Skywalker,876--67-8-34,"910 Tatooine Road, Tatooine",Y,N,910 Tatooine Road,Tatooine,None

In [43]:
#fill the empty column
df = df.fillna('')
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Stree Address,State,Zip
0,1001,Frodo,Baggins,123--54-5-54,"123 Shire Lane, Shire",Y,N,123 Shire Lane,Shire,
1,1002,Abed,Nadir,123--64-3-97,93 West Main Street,N,Y,93 West Main Street,,
2,1003,Walter,/White,,298 Drugs Driveway,N,,298 Drugs Driveway,,
3,1004,Dwight,Schrute,123--54-3-23,"980 Paper Avenue, Pennsylvania, 18503",Y,Y,980 Paper Avenue,Pennsylvania,18503
4,1005,Jon,Snow,876--67-8-34,123 Dragons Road,Y,N,123 Dragons Road,,
5,1006,Ron,Swanson,304--76-2-24,768 City Parkway,Y,Y,768 City Parkway,,
6,1007,Jeff,Winger,,1209 South Street,N,N,1209 South Street,,
7,1008,Sherlock,Holmes,876--67-8-34,98 Clue Drive,N,N,98 Clue Drive,,
8,1009,Gandalf,,,123 Middle Earth,Y,,123 Middle Earth,,
9,1010,Peter,Parker,123--54-5-54,"25th Main Street, New York",Y,N,25th Main Street,New York,
10,1011,Samwise,Gamgee,,"612 Shire Lane, Shire",Y,N,612 Shire Lane,Shire,
11,1012,Harry,...Potter,,2394 Hogwarts Avenue,Y,,2394 Hogwarts Avenue,,
12,1013,Don,Draper,123--54-3-23,2039 Main Street,Y,N,2039 Main Street,,
13,1014,Leslie,Knope,876--67-8-34,343 City Parkway,Y,N,343 City Parkway,,
14,1015,Toby,Flenderson_,304--76-2-24,214 HR Avenue,N,N,214 HR Avenue,,
15,1016,Ron,Weasley,123--54-5-54,2395 Hogwarts Avenue,N,N,2395 Hogwarts Avenue,,
16,1017,Michael,Scott,123--64-3-97,"121 Paper Avenue, Pennsylvania",Y,N,121 Paper Avenue,Pennsylvania,
17,1018,Clark,Kent,,3498 Super Lane,Y,,3498 Super Lane,,
18,1019,Creed,Braton,,,,Y,,,
19,1020,Anakin,Skywalker,876--67-8-34,"910 Tatooine Road, Tatooine",Y,N,910 Tatooine Road,Tatooine,
20,1020,Anakin,Skywalker,876--67-8-34,"910 Tatooine Road, Tatooine",Y,N,910 Tatooine Road,Tatooine,

In [46]:
#remove the when the do-not-contact is yes (Y)
for x in df.index:
    if df.loc[x, 'Do_Not_Contact'] == 'Y':
        df.drop(x, inplace = True)
        
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Stree Address,State,Zip
0,1001,Frodo,Baggins,123--54-5-54,"123 Shire Lane, Shire",Y,N,123 Shire Lane,Shire,
2,1003,Walter,/White,,298 Drugs Driveway,N,,298 Drugs Driveway,,
4,1005,Jon,Snow,876--67-8-34,123 Dragons Road,Y,N,123 Dragons Road,,
6,1007,Jeff,Winger,,1209 South Street,N,N,1209 South Street,,
7,1008,Sherlock,Holmes,876--67-8-34,98 Clue Drive,N,N,98 Clue Drive,,
8,1009,Gandalf,,,123 Middle Earth,Y,,123 Middle Earth,,
9,1010,Peter,Parker,123--54-5-54,"25th Main Street, New York",Y,N,25th Main Street,New York,
10,1011,Samwise,Gamgee,,"612 Shire Lane, Shire",Y,N,612 Shire Lane,Shire,
11,1012,Harry,...Potter,,2394 Hogwarts Avenue,Y,,2394 Hogwarts Avenue,,
12,1013,Don,Draper,123--54-3-23,2039 Main Street,Y,N,2039 Main Street,,
13,1014,Leslie,Knope,876--67-8-34,343 City Parkway,Y,N,343 City Parkway,,
14,1015,Toby,Flenderson_,304--76-2-24,214 HR Avenue,N,N,214 HR Avenue,,
15,1016,Ron,Weasley,123--54-5-54,2395 Hogwarts Avenue,N,N,2395 Hogwarts Avenue,,
16,1017,Michael,Scott,123--64-3-97,"121 Paper Avenue, Pennsylvania",Y,N,121 Paper Avenue,Pennsylvania,
17,1018,Clark,Kent,,3498 Super Lane,Y,,3498 Super Lane,,
19,1020,Anakin,Skywalker,876--67-8-34,"910 Tatooine Road, Tatooine",Y,N,910 Tatooine Road,Tatooine,

In [47]:
#remove the phone number when this is empty
for x in df.index:
    if df.loc[x, 'Phone_Number'] == '':
        df.drop(x, inplace = True)
        
df

C:\Users\ASUS\AppData\Local\Temp\ipykernel_4200\2576423839.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop(x, inplace = True)
C:\Users\ASUS\AppData\Local\Temp\ipykernel_4200\2576423839.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop(x, inplace = True)
C:\Users\ASUS\AppData\Local\Temp\ipykernel_4200\2576423839.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop(x, inplace = True)
C:\Users\ASUS\AppData\Local\Temp\ipykernel_4200\2576423839.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop(x, inplace = True)
C:\Users\ASUS\AppData\Local\Temp\ipykernel_4200\2576423839.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop(x, inplace = True)
C:\Users\ASUS\AppData\Local\Temp\ipykernel_4200\2576423839.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop(x, inplace = True)

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Stree Address,State,Zip
0,1001,Frodo,Baggins,123--54-5-54,"123 Shire Lane, Shire",Y,N,123 Shire Lane,Shire,
4,1005,Jon,Snow,876--67-8-34,123 Dragons Road,Y,N,123 Dragons Road,,
7,1008,Sherlock,Holmes,876--67-8-34,98 Clue Drive,N,N,98 Clue Drive,,
9,1010,Peter,Parker,123--54-5-54,"25th Main Street, New York",Y,N,25th Main Street,New York,
12,1013,Don,Draper,123--54-3-23,2039 Main Street,Y,N,2039 Main Street,,
13,1014,Leslie,Knope,876--67-8-34,343 City Parkway,Y,N,343 City Parkway,,
14,1015,Toby,Flenderson_,304--76-2-24,214 HR Avenue,N,N,214 HR Avenue,,
15,1016,Ron,Weasley,123--54-5-54,2395 Hogwarts Avenue,N,N,2395 Hogwarts Avenue,,
16,1017,Michael,Scott,123--64-3-97,"121 Paper Avenue, Pennsylvania",Y,N,121 Paper Avenue,Pennsylvania,
19,1020,Anakin,Skywalker,876--67-8-34,"910 Tatooine Road, Tatooine",Y,N,910 Tatooine Road,Tatooine,

In [49]:
#drop the 'Address' column
df = df.drop(columns = 'Address')
df

,CustomerID,First_Name,Last_Name,Phone_Number,Paying Customer,Do_Not_Contact,Stree Address,State,Zip
0,1001,Frodo,Baggins,123--54-5-54,Y,N,123 Shire Lane,Shire,
4,1005,Jon,Snow,876--67-8-34,Y,N,123 Dragons Road,,
7,1008,Sherlock,Holmes,876--67-8-34,N,N,98 Clue Drive,,
9,1010,Peter,Parker,123--54-5-54,Y,N,25th Main Street,New York,
12,1013,Don,Draper,123--54-3-23,Y,N,2039 Main Street,,
13,1014,Leslie,Knope,876--67-8-34,Y,N,343 City Parkway,,
14,1015,Toby,Flenderson_,304--76-2-24,N,N,214 HR Avenue,,
15,1016,Ron,Weasley,123--54-5-54,N,N,2395 Hogwarts Avenue,,
16,1017,Michael,Scott,123--64-3-97,Y,N,121 Paper Avenue,Pennsylvania,
19,1020,Anakin,Skywalker,876--67-8-34,Y,N,910 Tatooine Road,Tatooine,